# Generated by Django 5.2.1 on 2025-05-31 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElectronLugatModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ru', models.CharField(max_length=150, unique=True)),
                ('uz_kiril', models.CharField(max_length=150, unique=True)),
                ('uz_lotin', models.CharField(max_length=150, unique=True)),
                ('en', models.CharField(max_length=150, unique=True)),
                ('tr', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': "Elektron Lug'at",
            },
        ),
    ]
