# Generated by Django 5.2.1 on 2025-05-31 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='electronlugatmodel',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
